name: Build Spotify Downloader

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Consente di eseguire manualmente dall'interfaccia di GitHub
  workflow_dispatch:

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: windows-latest
            asset_name: Spotify-Downloader-Windows
            pyinstaller_args: --name="Spotify-Downloader" --windowed gui.py --clean
          - os: macos-latest
            asset_name: Spotify-Downloader-macOS
            pyinstaller_args: --name="Spotify-Downloader" --windowed gui.py --clean
          - os: ubuntu-latest
            asset_name: Spotify-Downloader-Linux
            pyinstaller_args: --name="Spotify-Downloader" --windowed gui.py --clean

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install FFmpeg (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install FFmpeg (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install ffmpeg

      - name: Install FFmpeg (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install ffmpeg -y
        shell: powershell

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Create assets directory
        run: |
          mkdir -p assets

      - name: Build with PyInstaller
        run: |
          pyinstaller ${{ matrix.pyinstaller_args }}

      - name: Package Windows application
        if: matrix.os == 'windows-latest'
        run: |
          cd dist
          7z a -tzip ${{ matrix.asset_name }}.zip "Spotify-Downloader"
        shell: pwsh

      - name: Package macOS application
        if: matrix.os == 'macos-latest'
        run: |
          cd dist
          zip -r ${{ matrix.asset_name }}.zip "Spotify-Downloader.app"

      - name: Package Linux application
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd dist
          tar -czvf ${{ matrix.asset_name }}.tar.gz "Spotify-Downloader"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.asset_name }}
          path: |
            dist/*.zip
            dist/*.tar.gz

      # Opzionale: Crea un rilascio quando viene taggato (es. v1.0.0)
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.zip
            dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}